.swiftlint.yml disabled_rules:
  - trailing_whitespace

included:
  - ios_agent/DualSizeAgent

excluded:
  - ios_agent/DualSizeAgent/Assets.xcassets

opt_in_rules:
  - empty_count
  - missing_docs
  - file_header

line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 600
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "github-actions-logging"
